In [12]:
import numpy as np

new_array = np.array([[2,7], [8,2]])
two_array = np.array([[1,4], [1,1]])
print(two_array)
print(new_array)


[[1 4]
 [1 1]]
[[2 7]
 [8 2]]


In [13]:
print(two_array * new_array)

[[ 2 28]
 [ 8  2]]
