In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [9]:
x = np.array([[1,2], [3,4], [5,6]])
x

array([[1, 2],
       [3, 4],
       [5, 6]])

In [10]:
np.ndim(x)

2

In [11]:
x.shape

(3, 2)

In [13]:
A = np.array([[1,2], [3,4]])
B = np.array([[5,6], [7,8]])

In [14]:
A * B

array([[ 5, 12],
       [21, 32]])

In [15]:
np.dot(A, B)

array([[19, 22],
       [43, 50]])

In [16]:
C = np.array([[1,2,3], [4,5,6]])
D = np.array([[1,2], [3,4], [5,6]])
np.dot(C, D)

array([[22, 28],
       [49, 64]])

In [27]:
E = np.array([[1,2,3], [2], [3],)
F = np.array([[1,2,3,4]])
print(E.shape)
print(F.shape)
E

(4, 1)
(1, 4)


array([[1],
       [2],
       [3],
       [4]])

In [28]:
F

array([[1, 2, 3, 4]])

In [29]:
np.dot(E, F)

array([[ 1,  2,  3,  4],
       [ 2,  4,  6,  8],
       [ 3,  6,  9, 12],
       [ 4,  8, 12, 16]])

In [30]:
G = np.array([[1,2,3,4], [5,6,7,8]])
np.dot(D, G)

array([[11, 14, 17, 20],
       [23, 30, 37, 44],
       [35, 46, 57, 68]])

In [31]:
A = np.array([[1,2], [3, 4], [5,6]])
A.shape

(3, 2)

In [32]:
B = np.array([7,8])
B.shape

(2,)

In [33]:
np.dot(A, B)

array([23, 53, 83])

In [34]:
np.dot(B, A)

ValueError: shapes (2,) and (3,2) not aligned: 2 (dim 0) != 3 (dim 0)

In [35]:
X = np.array([1, 2])
X.shape

(2,)

In [36]:
W = np.array([[1, 3, 5], [2, 4, 6]])
print(W)
W.shape

[[1 3 5]
 [2 4 6]]


(2, 3)

In [37]:
Y = np.dot(X, W)
print(Y)

[ 5 11 17]


In [38]:
Z = np.dot(W, X)
print(Z)

ValueError: shapes (2,3) and (2,) not aligned: 3 (dim 1) != 2 (dim 0)

In [40]:
Y.shape

(3,)

In [41]:
W.ndim

2

In [42]:
Y.ndim

1